server:
  port: 6001

spring:
  application:
    name: feign-web
feign:
  hystrix:
    enabled: true #默认为false，如果想用断路由，要打开这个设置

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true