server:
  port: 8001
  
spring:
   application:
    name: user-server

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: producer-server8001-hystrix   #自定义hystrix相关的服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址


hystrix:
  command:
     default: #所有方法有效
        execution:
           isolation:
              thread:
                 timeoutInMilliseconds: 2000 #默认1秒：（方法上记得要加上@HystrixCommand，否则无效）：
     listUserMethod: #方法名称为listUserMethod有效
        execution:
           isolation:
              thread:
                 timeoutInMilliseconds: 5000 #配置具体方法的超时时间
info:
  app.name: smartcity
  company.name: novo
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      
      
      
 

